Included OpenJ9DiagnosticsMXBean Demo
ibmruntimes/OpenJ9DiagnosticsMXBeanDemo pull request #1
Opened 2018-06-12 19:45 UTC by chandrams

Signed-off-by: Chandrakala <chandra-ms@in.ibm.com>

2018-06-20 10:12 UTC, dinogun requested changes

2018-06-20 10:12 UTC, dinogun commented on README.md
> +# OpenJ9DiagnosticsMXBeanDemo
Please update the README to have instructions to do the deploy to ICP.

2018-06-20 10:12 UTC, dinogun commented on hello-deploy-dockerhub.yaml
> +            server: <IP Addr of NFS Server>
Indicate that the NFS server setup needs to be done prior to running this demo in the README. You can also point to relevant ICP links if required.

2018-06-21 06:38 UTC, chandrams commented on hello-deploy-dockerhub.yaml
> +            server: <IP Addr of NFS Server>
I have updated the README, please review. Thanks.

2018-06-28 08:18 UTC, dinogun approved these changes

2018-06-28 08:18 UTC, merged